import streamlit as st
import pandas as pd
import pydeck as pdk
df=pd.read_csv("../Data/airbnb_investment_dataset.csv")
st.set_page_config(
    page_title="Airbnb Investment Advisor",
    page_icon="🏠",
    layout="wide"
)
st.markdown("""
<style>
.block-container{
    padding-top:2rem;
}
[data-testid="stMetricValue"]{
    color:#00C853;
}
h1{
    color:#FF6F00;
}
</style>
""",unsafe_allow_html=True)


st.title("🏠Airbnb Investment Advisor")
with st.expander("📖 About This Project"):
    st.write("""
    This dashboard helps investors identify high-potential Airbnb opportunities in London using revenue, occupancy, guest ratings and a custom Investment Score.
    """)
with st.expander("📖How are Investment Scores calculated"):
    st.markdown("""
    This platform evaluates Airbnb investment opportunities using three key factors:

    **Revenue Potential (50%)**
    - Estimated annual revenue generated by a property.
    
    **Occupancy Rate (30%)**
    - Percentage of days booked during the year.
    
    **Guest Rating (20%)**
    - Average review score from guests.
    
    These variables are normalized using Min-Max Scaling and combined into a weighted Investment Score.

    ### Investment Score Formula
    Investment Score =
    (0.5 × Revenue Score)+
    (0.3 × Occupancy Score)+
    (0.2 × Rating Score)

    ### Investment Grades
    - Grade A = Top 25% of properties → Excellent Investment
    - Grade B = 50-75th percentile → Good Investment
    - Grade C = 25-50th percentile → Average Investment
    - Grade D = Bottom 25% → Weak Investment
    """)
st.markdown("Identify the best Airbnb investment opportunities in London using revenue, occupancy, ratings and investment scores.")



tab1,tab2,tab3=st.tabs([
        "📊 Dashboard",
        "🏠 Property Search",
        "📍 Neighbourhood Explorer"
    ])

with tab1:
    st.subheader("Market Overview")
    col1,col2,col3,col4,col5=st.columns(5)
    col1.metric("Total Listings",f"{len(df):,}")
    col2.metric("Average Revenue",f"£{int(df['estimated_revenue_l365d'].mean()):,}")
    col3.metric("Average Occupancy",f"{round(df['occupancy_rate'].mean(),1)}%")
    col4.metric("Average Rating",round(df['review_scores_rating'].mean(),2))
    col5.metric("Top Score",round(df["investment_score"].max(),1))



    st.subheader("💰Top Revenue Neighbourhoods")
    st.caption("Neighbourhoods ranked by average estimated annual Airbnb revenue per listing.")
    revenue_area=(df.groupby("neighbourhood_cleansed")["estimated_revenue_l365d"].mean().sort_values(ascending=False).head(10))
    st.bar_chart(revenue_area)



    st.subheader("📍Top 10 Investment Areas")
    st.caption("Areas ranked by average Investment Score, highlighting neighbourhoods with the strongest overall Airbnb investment potential.")
    top_area = (df.groupby("neighbourhood_cleansed").agg({
        "estimated_revenue_l365d":"mean",
        "occupancy_rate":"mean",
        "investment_score":"mean"})
        .sort_values("investment_score",ascending=False).head(10).round(2))
    top_area = top_area.rename(columns={
    "estimated_revenue_l365d":"Avg Revenue (£)",
    "occupancy_rate":"Avg Occupancy %",
    "investment_score":"Avg Investment Score"})
    top_area.index.name = "Area"
    st.dataframe(top_area, hide_index=False)



    st.subheader("Room Type Performance")
    st.caption("Average annual revenue generated by each room type.")
    room_perf = (df.groupby("room_type")["estimated_revenue_l365d"].mean().sort_values(ascending=False))
    st.bar_chart(room_perf)

    
with tab2:
    st.subheader("Investment Filters")
    neighbourhood=st.selectbox("Neighbourhood",
sorted(df["neighbourhood_cleansed"].dropna().unique()))
    room_type=st.selectbox("Room Type",sorted(df["room_type"].dropna().unique()))
    min_rating=st.slider("Minimum rating",0.0,5.0,4.0)
    grade=st.selectbox("Investment Grade",sorted(df["investment_grade"].dropna().unique()))

    filtered_df=df[
        (df["neighbourhood_cleansed"]==neighbourhood)&
        (df["room_type"]==room_type)&
        (df["review_scores_rating"]>=min_rating)&
        (df["investment_grade"]==grade)]

    st.subheader("Recommended Properties")
    st.write("Number of recommended properties:", len(filtered_df))
    if len(filtered_df)>0:
          display_df=(
            filtered_df[[
                "name",
                "neighbourhood_cleansed",
                "room_type",
                "review_scores_rating",
                "occupancy_rate",
                "investment_score",
                "estimated_revenue_l365d"
            ]].rename(columns={
            "name": "Property",
            "neighbourhood_cleansed": "Area",
            "room_type": "Room Type",
            "review_scores_rating": "Rating ⭐",
            "occupancy_rate": "Occupancy %",
            "investment_score": "Investment Score",
            "estimated_revenue_l365d": "Annual Revenue(£)"
        }).sort_values("Investment Score", ascending=False).head(20))
    else:
        st.warning("No properties match the selected filters.")
    display_df["Annual Revenue(£)"]=(display_df["Annual Revenue(£)"].apply(lambda x:f"£{x:,.0f}"))
    csv=display_df.to_csv(index=False)
    st.download_button("📥 Download Recommendations",csv,"recommended_properties.csv","text/csv")
    st.dataframe(display_df, use_container_width=True,hide_index=True)



    st.subheader("Top 10 Investment Opportunities")
    st.caption("Individual properties ranked by Investment Score based on revenue potential (50%), occupancy rate (30%) and guest ratings (20%).")
    top10=(
        df.sort_values("investment_score", ascending=False).head(10)
          .rename(columns={
          "name": "Property",
          "neighbourhood_cleansed": "Area",
          "investment_grade": "Grade",
          "investment_score": "Investment Score",
          "estimated_revenue_l365d": "Annual Revenue(£)",
          "occupancy_rate": "Occupancy %"
      }))
    st.dataframe(top10[[
            "Property",
            "Area",
            "Grade",
            "Investment Score",
            "Annual Revenue(£)",
            "Occupancy %"
        ]],use_container_width=True,hide_index=True)


with tab3:
    st.subheader("Neighbourhood Explorer")
    selected_area=st.selectbox("Choose Area",sorted(df["neighbourhood_cleansed"].unique()))
    area_df=df[df["neighbourhood_cleansed"]==selected_area]
    c1,c2,c3,c4=st.columns(4)
    c1.metric("Listings",f"{len(area_df):,}")
    c2.metric("Avg Revenue",f"£{int(area_df['estimated_revenue_l365d'].mean()):,}")
    c3.metric("Avg Occupancy",f"{round(area_df['occupancy_rate'].mean(),1)}%")
    c4.metric("Avg Rating",round(area_df['review_scores_rating'].mean(),2))

    st.subheader(f"🗺️ Airbnb Locations in {selected_area}")
    map_df = area_df[[
            "name",
            "latitude",
            "longitude",
            "investment_score",
            "estimated_revenue_l365d",
            "review_scores_rating"
    ]].copy()
    layer = pdk.Layer(
            "ScatterplotLayer",
            data=map_df,
            get_position=["longitude", "latitude"],
            get_radius=60,
            get_fill_color=[255, 87, 34, 180],
            pickable=True)
    tooltip = {
        "html": """
        <b>Property:</b> {name}<br/>
        <b>Investment Score:</b> {investment_score}<br/>
        <b>Annual Revenue:</b> £{estimated_revenue_l365d}<br/>
        <b>Rating:</b> {review_scores_rating}
        """,
        "style": {
            "backgroundColor": "black",
            "color": "white"
        }
    }
    st.pydeck_chart(
        pdk.Deck(
            map_style="mapbox://styles/mapbox/light-v9",
            initial_view_state=pdk.ViewState(
                latitude=area_df["latitude"].mean(),
                longitude=area_df["longitude"].mean(),
                zoom=11,
                pitch=0
            ),
            layers=[layer],
            tooltip=tooltip))


    
    st.subheader(f"Top Properties in {selected_area}")
    top_area_props=(area_df.sort_values("investment_score",ascending=False).head(10))
    top_area_props_display=(
    top_area_props[[
            "name",
            "investment_score",
            "estimated_revenue_l365d",
            "review_scores_rating"]].rename(columns={
            "name": "Property",
            "investment_score": "Investment Score",
            "estimated_revenue_l365d": "Annual Revenue (£)",
            "review_scores_rating": "Rating ⭐"}))
    top_area_props_display["Annual Revenue (£)"]=(top_area_props_display["Annual Revenue (£)"]
    .apply(lambda x: f"£{x:,.0f}"))
    st.dataframe(top_area_props_display,use_container_width=True,hide_index=True)
                                 
    
st.markdown("---")
st.caption("Airbnb Investment Advisor | London Market Analysis | Built with Python, SQL and Streamlit | By Ananya Kastiya")



















